<?php
declare(strict_types=1);

ob_start(); // turn on output buffering

// Define paths
define("PRIVATE_PATH", dirname(__FILE__));
define("PROJECT_PATH", dirname(PRIVATE_PATH));
define("PUBLIC_PATH", PROJECT_PATH . "/public_html");
define("SHARED_PATH", PRIVATE_PATH . "/shared");

if ($_SERVER['SERVER_NAME'] == 'localhost') {
  require('debug.php'); // is used in site debug

  $public_end = strpos($_SERVER['SCRIPT_NAME'], '/public_html') + 12;
  $doc_root = substr($_SERVER['SCRIPT_NAME'], 0, $public_end);

} else {
  $doc_root = '';
}

// Site's root URL (base URL)
define("WWW_ROOT", $doc_root);

// Image settings
define("MAX_FILE_SIZE", 614400); // 600 KB, 0.6 MB
define("POST_IMG_MAX_NUM", 10);
define("IMAGES_PATH", PUBLIC_PATH . '/assets/images' );

/**
 * Secret key to generate a User token
 * Can be used for any other 256-bit key requirement
 * This key generated by https://randomkeygen.com/
 * Please, get another key in randomkeygen.com for your data security!
 * It must be 32 characters long.
 */
define("SECRET_KEY", "jaItYP0KmKp6wcWCCkCKrxMEVT0yIdqn");

// SMTP
require_once('smtp_settings.php');

// Functions
require_once('functions.php');
require_once('db_credentials.php');
require_once('db_functions.php');
require_once('validation_functions.php');
require_once('status_error_functions.php');
require_once(PROJECT_PATH . '/vendor/autoload.php');

// Database connection
$database = db_connect();
App\Classes\DatabaseObject::setDatabase($database);

// Is used globally in pages
$session = new App\Classes\Session;

$json = file_get_contents(PUBLIC_PATH . '/staff/site/user-site-data.json');

// Is used globally in pages
$jsonstore = json_decode($json);
$jsonarray = json_decode($json, true);

// Pagination settings
define("DASHBOARD_PER_PAGE", $jsonstore->perPageNumBackend);
define("FRONTEND_PER_PAGE", $jsonstore->perPageNumFrontend);
define("TABLE_SIZE", $jsonstore->tableSize);

/**
 * Pass php variables to javascript in array
 *
 * @return string
 */
function pass_to_js() {
  global $session;
  global $jsonstore;

  $server['baseUrl'] = WWW_ROOT;
  $server['isLoggedIn'] = $session->isLoggedIn();
  $server['isAuthor'] = $session->isAuthor();
  $server['isAdmin'] = $session->isAdmin();
  $server['userId'] = $session->isLoggedIn() ? $session->getUserId() : 0;
  $server['singlePost'] = (url_contain('/post/')) ? $_GET['id'] : false;
  $server['dashboardMain'] = (url_contain('staff/index')) ? true : false;
  $server['postFontSize'] = $jsonstore->postFontSize;
  $server['slider'] = $jsonstore->slider;
  $server['maxFileSize'] = MAX_FILE_SIZE;
  $server['postImgMaxNum'] = POST_IMG_MAX_NUM;

  $script = '<script>';
  $script .= 'var server = ' . json_encode($server);
  $script .= '</script>';

  return $script;
}

?>